#!/usr/bin/env python3
"""
CLEP Playlist Generator CLI Tool
Autodetects MP3 files in a directory and generates a playlist.js file for the HTML player.
"""

import os
import re
import sys
import json
import logging

# Setup Logger with standard formatting
logging.basicConfig(
    level=logging.INFO,
    format='[%(levelname)s] %(asctime)s - %(message)s',
    datefmt='%H:%M:%S'
)
logger = logging.getLogger(__name__)

try:
    import click
except ImportError:
    logger.error("The 'click' package is required. Please install it with 'pip install click'.")
    sys.exit(1)


def natural_sort_key(s):
    """
    Key function for natural alphanumeric sorting (e.g. "2.1" comes before "10.1").
    """
    return [int(text) if text.isdigit() else text.lower() for text in re.split(r'(\d+)', s)]


@click.command()
@click.option(
    '--dir', '-d', 
    default='.', 
    help='Directory containing the audio files to scan.', 
    type=click.Path(exists=True, file_okay=False, dir_okay=True, readable=True)
)
@click.option(
    '--output', '-o', 
    default='playlist.js', 
    help='Output Javascript file path.',
    type=click.Path()
)
def generate_playlist(dir, output):
    """
    Scans the specified directory for MP3 files and generates a playlist.js file.
    """
    logger.info(f"Scanning directory: {os.path.abspath(dir)}")
    
    try:
        # Input Validation: List contents of target directory
        all_files = os.listdir(dir)
    except Exception as e:
        logger.error(f"Failed to read directory {dir}: {e}")
        sys.exit(1)

    # Filter for mp3 files
    mp3_files = [f for f in all_files if f.lower().endswith('.mp3')]
    
    if not mp3_files:
        logger.warning("No MP3 files found in the target directory.")
        # Proceed to write an empty playlist.js to reset or initialize it
    
    # Sort files naturally
    mp3_files.sort(key=natural_sort_key)
    logger.info(f"Found {len(mp3_files)} MP3 audio file(s).")

    # Construct JavaScript file content
    output_path = os.path.join(dir, output) if not os.path.isabs(output) else output
    
    js_content = (
        "// Auto-generated playlist file. Do not edit manually.\n"
        "// Generated by: generate_playlist.py\n\n"
        "const tracks = [\n"
    )
    for filename in mp3_files:
        # Escape double quotes in filename if any exist
        escaped_name = filename.replace('"', '\\"')
        js_content += f'  "{escaped_name}",\n'
    
    # Remove trailing comma and close array
    if mp3_files:
        js_content = js_content[:-2] + "\n"
    js_content += "];\n"

    try:
        # Write content out securely
        with open(output_path, 'w', encoding='utf-8') as f:
            f.write(js_content)
        logger.info(f"Successfully generated playlist file at: {os.path.abspath(output_path)}")
        click.echo(f"Success! {len(mp3_files)} tracks saved to {output}")
    except Exception as e:
        logger.error(f"Failed to write playlist file: {e}")
        sys.exit(1)


if __name__ == '__main__':
    generate_playlist()
